---
- name: Tomcat Setup
  user: root
  hosts: all
  gather_facts: no
  tasks:
   - name: Tomcate Setup
     copy:
       src: /root/apache-tomcat-8.5.70
       dest: /opt/
       mode: 0755
   - name: Starting the tomcat
     shell: "sh /opt/apache-tomcat-8.5.70/bin/startup.sh"